version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    environment:
      - CHROME_BIN: /usr/bin/google-chrome
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies- # fallback for cache miss
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: npm run linter
